[licenses]
allow = [
    "MIT", "Apache-2.0", "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause", "BSD-3-Clause", "ISC", "Unicode-DFS-2016",
    "MPL-2.0", "Unicode-3.0", "CDLA-Permissive-2.0"
]

[advisories]
# "deny" makes advisories fail CI, "warn" only warns
# Allowed values: "allow", "warn", "deny"
vulnerability = "deny"
unsound = "deny"
unmaintained = "deny"
yanked = "warn"

# Temporarily ignore advisories you cannot fix yet
ignore = [
    # gix ecosystem issues (wait for upstream updates)
    "RUSTSEC-2025-0021", # gix-features path traversal
    "RUSTSEC-2024-0348", # gix-index
    "RUSTSEC-2024-0350", # gix-fs

    # Unmaintained crates (pulled in by tauri/gtk)
    "RUSTSEC-2025-0056", # adler
    "RUSTSEC-2025-0057", # fxhash
    "RUSTSEC-2021-0145", # atty
    "RUSTSEC-2025-0055", # atk
    "RUSTSEC-2025-0054", # gdk
]

# Optional: control freshness of advisory DB
maximum-db-staleness = "7d"
