// Page exports
export { default as Dashboard } from './Dashboard'
export { default as FileManagement } from './FileManagement'
export { default as FileWatcher } from './FileWatcher'
export { default as Deduplication } from './Deduplication'
export { default as ProgressDashboard } from './ProgressDashboard'
export { default as Workspace } from './Workspace'
export { default as Settings } from './Settings'
export { default as Search } from './Search'
export { default as DocumentComparison } from './DocumentComparison'
export { default as DocumentIndex } from './DocumentIndex'
