name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  # Set consistent environment for tests
  PROXEMIC_ENV: development
  RUST_ENV: test
  RUST_LOG: info
  CI: true
  GITHUB_ACTIONS: true
  # Mock user directories for headless CI - CRITICAL FOR TESTS
  HOME: /tmp/mock_home
  XDG_DESKTOP_DIR: /tmp/mock_home/Desktop
  XDG_DOCUMENTS_DIR: /tmp/mock_home/Documents
  XDG_DOWNLOAD_DIR: /tmp/mock_home/Downloads

jobs:
  test-rust:
    name: Test Rust Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up mock user directories
        run: |
          mkdir -p /tmp/mock_home/Desktop
          mkdir -p /tmp/mock_home/Documents
          mkdir -p /tmp/mock_home/Downloads
          chmod 755 /tmp/mock_home/Desktop
          chmod 755 /tmp/mock_home/Documents
          chmod 755 /tmp/mock_home/Downloads
          touch /tmp/mock_home/Documents/test.txt
          touch /tmp/mock_home/Downloads/test.csv

      - name: Install Tauri dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      # FIXED: Clear cache and force dependency resolution
      - name: Clean Rust cache and dependencies
        run: |
          cargo clean
          rm -f Cargo.lock
        working-directory: src-tauri

      # FIXED: Cache after cleaning, with better cache key
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          # Add cache key that includes Cargo.toml hash
          key: ${{ runner.os }}-cargo-${{ hashFiles('src-tauri/Cargo.toml') }}

      # FIXED: Force dependency update before any compilation
      - name: Update dependencies
        run: |
          cargo update
          cargo fetch
        working-directory: src-tauri

      - name: Debug environment and dependencies
        run: |
          echo "=== Environment Debug ==="
          echo "PWD: $PWD"
          echo "HOME: $HOME"
          echo "CI: $CI"
          echo "GITHUB_ACTIONS: $GITHUB_ACTIONS"
          echo "PROXEMIC_ENV: $PROXEMIC_ENV"
          echo "RUST_ENV: $RUST_ENV"
          echo "RUST_LOG: $RUST_LOG"
          echo ""
          echo "=== Rust/Cargo Debug ==="
          cargo version
          rustc --version
          echo ""
          echo "=== Dependencies Check ==="
          cargo tree --depth=1 | grep -E "(rand|once_cell|jsonschema)" || echo "Dependencies not found in tree"
          echo ""
          echo "=== Cargo.toml content ==="
          cat Cargo.toml | grep -E "(rand|once_cell|jsonschema)" || echo "Dependencies not found in Cargo.toml"
        working-directory: src-tauri

      - name: Check formatting
        run: cargo fmt --all -- --check
        working-directory: src-tauri

      - name: Run Clippy
        run: cargo clippy -- -D warnings
        working-directory: src-tauri

      - name: Run tests with isolation
        run: cargo test -- --test-threads=1 --nocapture
        working-directory: src-tauri

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Run tests
        run: npm run test -- --passWithNoTests

      - name: Build frontend
        run: npm run build

  build-tauri:
    name: Build Tauri App
    needs: [test-rust, test-frontend]
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # FIXED: Clean cache for build job too
      - name: Clean dependencies
        run: |
          cargo clean
          rm -f Cargo.lock
        working-directory: src-tauri

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      # FIXED: Update dependencies in build job
      - name: Update dependencies
        run: |
          cargo update
          cargo fetch
        working-directory: src-tauri

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm ci

      - name: Install Tauri dependencies (Ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Build Tauri app
        run: npm run tauri build
